// <auto-generated />
using System;
using CRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Data.Migrations
{
    [DbContext(typeof(EntitiesDbContext))]
    [Migration("20231117041307_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantID");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantID = new Guid("9b3f7c3f-43a6-46c9-8c69-d59effc0652f"),
                            TenantName = "Tenant 1"
                        },
                        new
                        {
                            TenantID = new Guid("b63674c5-4cb5-40c4-a41f-90450d96b010"),
                            TenantName = "Tenant 2"
                        },
                        new
                        {
                            TenantID = new Guid("6e5e254e-692b-47ea-b1ad-1f589a14eebc"),
                            TenantName = "Tenant 3"
                        },
                        new
                        {
                            TenantID = new Guid("ab0d651f-eeb6-4d8b-b1f5-db5bbe4cfd42"),
                            TenantName = "Tenant 4"
                        },
                        new
                        {
                            TenantID = new Guid("607debc9-1d16-47fe-badf-1bf98b1c40c6"),
                            TenantName = "Tenant 5"
                        },
                        new
                        {
                            TenantID = new Guid("298ba02c-723c-4cbb-a6bb-7a433ad8fa28"),
                            TenantName = "Tenant 6"
                        });
                });

            modelBuilder.Entity("CRM.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("TenantID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CRM.Entities.User", b =>
                {
                    b.HasOne("CRM.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CRM.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
